from datetime import date
from KeyGeneration import generateKey

class Deck:
    name = ""
    cards = []
    creation_date = ""
    id = ""

    def __init__(self, name, cards):
        """
        Constructor that intializes the card with its autogenerated data, also sets
        the name of the deck and the cards that compose it.

        :name: string with the name of the deck.
        :cards: list with the cards that are part of the deck.
        """
        self.name = name

        self.creation_date = date.today()
        id = "D-" + generateKey()

        self.addCards(cards)

    def setName(self, name):
        self.name = name

    def getName(self):
        return self.name
    
    def getCreationDate(self):
        return self.creation_date

    def addCards(self, cards):
        self.cards = cards

    def getCards(self):
        return self.cards

    def isValid(self):
        """
        isValid checks every card in the deck to see if they are active in game.

        :return: True if all cards are active, False otherwise.
        """
        for i in self.cards:
            if not i.gameActive():
                return False
        return True