from logic.User import *

class Admin(User):
    role = ""

    def __init__(self):
        """
        Constructor that intializes the admin with its autogenerated data.
        """
        User.__init__(self, ["A-"])

    def setRole(self, role):
        self.role = role

    def getRole(self):
        return self.role         