from datetime import date
from commons.KeyGeneration import generateKey

class Card:
    name = ""
    description = ""
    main = True
    variant_name = ""
    creation_date = None
    last_modification = None
    race = ""
    rarity = ""
    image = ""
    game_active = True
    pull_active = True
    turn_power = 0
    bonus_power = 0
    stats = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    total_power = 0
    name_id = ""
    var_id = ""

    def __init__(self, name_id):
        """
        Constructor that intializes the card with its autogenerated data, also receives the name id 
        which could be empty, if it is, the id is generated otherwise the card being main is set to false
        and the given name id is used and only generates the variant id.
        """
        self.creation_date = date.today()
        self.last_modification = self.creation_date
        if name_id == "":
            self.name_id = generateKey(["C-"])
        else:
            self.name_id = name_id
            self.main = False
        self.var_id = generateKey(["V-"])

    def setStats(self, stats):
        """
        setStats receives a list of ints corresponding to the stats of the card, checks if all the stats
        are in the list, saves them and calculates the new total, this also updates the last modification date 
        """
        if len(stats) == 26:
            self.stats = stats
            for i in range(0, 25):
                self.total_power += self.stats[i]
            self.last_modification = date.today()

    def setName(self, name):
        self.name = name

    def getName(self):
        return self.name
    
    def setDescription(self, description):
        self.description = description

    def getDescription(self):
        return self.description
    
    def setVariantName(self, variant_name):
        self.variant_name = variant_name

    def getVariantName(self):
        return self.variant_name

    def setRace(self, race):
        self.race = race

    def getRace(self):
        return self.race

    def setRarity(self, rarity):
        self.rarity = rarity

    def getRarity(self):
        return self.rarity
    
    def gameActive(self):
        return self.game_active
    
    def pullActive(self):
        return self.pull_active
    
    def getID(self):
        return self.name_id + "-" + self.var_id
    
    def lastMod(self):
        return self.last_modification
    
    def setImage(self, image_name):
        self.image = image_name
    
    def getImage(self):
        return self.image
    
    def setTurnPower(self, turn_power):
        self.turn_power = turn_power
    
    def getTurnPower(self):
        return self.turn_power
    
    def setBonusPower(self, bonus_power):
        self.bonus_power = bonus_power
    
    def getBonusPower(self):
        return self.bonus_power
    
    def isMain(self):
        return self.main