from logic.User import *

class Player(User):
    username = ""
    country = ""
    avatar = ""
    exp = 0
    owned_cards = []
    decks = []
    selected_deck = None

    def __init__(self):
        """
        Constructor that intializes the player with its autogenerated data.
        """
        User.__init__(self, ["J-", "A-"])

    def setUser(self, username):
        self.username = username

    def getUser(self):
        return self.username

    def setCountry(self, country):
        self.country = country

    def getCountry(self):
        return self.country
    
    def setAvatar(self, image):
        self.avatar = image

    def getAvatar(self):
        return self.avatar
    
    def receiveCard(self, card, album):
        """
        receiveCards adds a card to the player's card list, then sorts the list.

        :card: card to give to the player.
        :album: CardAlbum class that sorts the list.
        """
        self.owned_cards.append(card)
        self.owned_cards = album.sort(self.owned_cards)

    def showCards(self):
        """
        showCards getter for the player owned cards.

        :return: list with the player owned cards.
        """
        return self.owned_cards

    def addDeck(self, deck):
        """
        addDeck adds a deck to the player's deck list.

        :deck: deck created by the player.
        """
        if len(self.decks) > 15:
            return -1
            
        self.decks.append(deck)
        return 0

    def showDecks(self):
        """
        showDecks getter for the player's decks.

        :return: list with the player's decks.
        """
        return self.decks

    def selectDeck(self, index):
        self.selected_deck = self.decks[index]

    def getSelectedDeck(self):
        return self.selected_deck

    def getWin(self):
        self.exp += 100         