from datetime import date
from commons.KeyGeneration import generateKey

class Player:
    name = ""
    username = ""
    password = ""
    mail = ""
    country = ""
    avatar = ""
    registration_date = ""
    player_id = ""
    username_id = ""
    exp = 0
    owned_cards = []
    decks = []

    def __init__(self):
        """
        Constructor that intializes the card with its autogenerated data.
        """
        self.registration_date = date.today()
        self.player_id = generateKey(["J-"]) 
        self.username_id = generateKey(["A-"])

    def setName(self, name):
        self.name = name

    def getName(self):
        return self.name

    def setUser(self, username):
        self.username = username

    def getUser(self):
        return self.username
    
    def setPassword(self, password):
        self.password = password

    def getPassword(self):
        return self.password
    
    def setMail(self, mail):
        self.mail = mail

    def getMail(self):
        return self.mail

    def setCountry(self, country):
        self.country = country

    def getCountry(self):
        return self.country
    
    def setAvatar(self, image):
        self.avatar = image

    def getAvatar(self):
        return self.avatar
    
    def receiveCard(self, card):
        """
        receiveCards adds a card to the player's card list, then sorts the list.

        :card: card to give to the player.
        """
        self.owned_cards.append(card)
        self.sortCards()

    def showCards(self):
        """
        showCards getter for the player owned cards.

        :return: list with the player owned cards.
        """
        return self.owned_cards
    
    def sortCards(self):
        """
        sortCards adds all the player's cards names in lowercase to a list to use python's sort, 
        then checks the name of the cards to place them in the order obtained with 
        the sort and updates the player's card list.
        """
        order = []
        for i in self.owned_cards:
            name = i.getName().lower()
            var = i.getVariantName().lower()
            order.append(name + var)
        order.sort()

        sorted_cards = []
        for j in range(0, len(order)):
            for k in self.owned_cards:
                name = k.getName().lower()
                var = k.getVariantName().lower()
                if (name + var) == order[j]:
                    sorted_cards.append(k)

        self.owned_cards = sorted_cards

    def addDeck(self, deck):
        """
        addDeck adds a deck to the player's deck list.

        :deck: deck created by the player.
        """
        if len(self.decks) > 15:
            return -1
            
        self.decks.append(deck)
        return 0

    def showDecks(self):
        """
        showDecks getter for the player's decks.

        :return: list with the player's decks.
        """
        return self.decks         