from datetime import date
from commons.KeyGeneration import generateKey

class User:
    name = ""
    mail = ""
    password = ""
    creation_date = ""
    id = ""

    def __init__(self, key_list):
        """
        Constructor that intializes the user with its autogenerated data.

        :key_list: list with strings to generate the corresponding key, depending on the type of user.
        """
        self.registration_date = date.today()
        self.id = generateKey(key_list)

    def setName(self, name):
        self.name = name

    def getName(self):
        return self.name
    
    def setMail(self, mail):
        self.mail = mail

    def getMail(self):
        return self.mail

    def setPassword(self, password):
        self.password = password

    def getPassword(self):
        return self.password
    
    def getCreationDate(self):
        return self.creation_date
    
    def getID(self):
        return self.id